#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 */
// Environment
require(__DIR__ . '/env.php');


require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/common/config/bootstrap.php';

$config = yii\helpers\ArrayHelper::merge(
    require __DIR__ . '/common/config/main.php',
    require __DIR__ . '/common/config/main-local.php'
);
Yii::$classMap['yii\db\mysql\JsonExpressionBuilder'] = '@common/replaces/JsonExpressionBuilder.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
